### PR TITLE
create secrets during provision

### PR DESCRIPTION
**Pull request by maleck13**
create secrets directly during provision. Add a bearer only client.

@aidenkeating want to give it a try. You should just need to provision key cloak from the apb again

### CODE REVIEW

**Comment by aidenkeating** [comment]
Taking a look now

**Comment by aidenkeating** [comment]
@maleck13 When I try to provision Keycloak no services are being created, I'm using the feedhenry org on DockerHub.

**Comment by aidenkeating** [comment]
@maleck13 I ***think*** the format of the client secret needs to be changed. There are two ways to initialise the client, by providing a URL to the Keycloak config endpoint or by providing the keycloak config object.

When providing a URL the client expects `config.resource` and `config.auth-server-url` to exist on the response from Keycloak.

When providing the config object directly it expects these to be renamed to `config.clientId` and `config.url` respectively.

At least this is my understanding from https://github.com/keycloak/keycloak-js-bower/blob/master/dist/keycloak.js#L580-L641 .

So we could just include the two extra values in the secret for the public client, or it can be mapped client-side. Any opinion on which approach to go for?

**Comment by maleck13** [comment]
Happy to have them done in the secret. Do you want to add these?

**Comment by maleck13** [comment]
@aidenkeating I know you were looking at these changes. Did you add your fix to the same branch or another PR?

**Comment by aidenkeating** [comment]
@maleck13 I think this is good to merge if you're happy with it

**Pull request merged**
